---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "acorn-init"
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: acorn-init-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: acorn-init
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: acorn-init-v010
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: acorn-init
          image: ghcr.io/acorn-io/acorn:v0.1.0
          command: ["acorn", "init", "--cluster-domains", "$CLUSTER_ID.k8s.civo.com"]
      restartPolicy: Never
      serviceAccountName: acorn-init
