apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: apps
  labels:
    name: jenkins-data
    type: longhorn
spec:
  capacity:
    storage: $VOLUME_SIZE
  volumeMode: Filesystem
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  csi:
    driver: io.rancher.longhorn
    fsType: ext4
    volumeAttributes:
      numberOfReplicates: '2'
      staleReplicaTimeout: '20'
    volumeHandle: jenkins-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  labels:
    type: longhorn
    app: jenkins
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $VOLUME_SIZE
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
  - name: jenkins
    port: 8080
    targetPort: 8080
  - name: jenkins-agent
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        tier: jenkins
    spec:
      containers:
      - image: bitnami/jenkins:2.190.1-debian-9-r14
        name: jenkins
        env:
        - name: JENKINS_USERNAME
          value: $JENKINS_USERNAME
        - name: JENKINS_PASSWORD
          value: $JENKINS_PASSWORD
        ports:
        - containerPort: 8080
          name: jenkins
        - containerPort: 50000
          name: jenkins-agent
        volumeMounts:
        - name: jenkins-persistent-storage
          mountPath: /bitnami
      volumes:
      - name: jenkins-persistent-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
